'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_consultaENVIRONMENTAL_docs
    
    '''<summary>
    '''lblt_titulo_pantalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_titulo_pantalla As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblt_subtitulo_pantalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_subtitulo_pantalla As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_review_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_review_type As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_RolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_RolID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_GroupRolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_GroupRolID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_ALL_RolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ALL_RolID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_ALL_SIMPLE_RolID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ALL_SIMPLE_RolID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmb_rev_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_rev_type As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''chk_allreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_allreview As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''lblt_starDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_starDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_finicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_finicio As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''chkfilterDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkfilterDate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblt_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_EndDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_ffin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ffin As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''lblt_keyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_keyword As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rdKeyWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdKeyWord As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''btn_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_buscar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btn_return control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_return As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''lblSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearch As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grd_cate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_cate As Global.Telerik.Web.UI.RadGrid
End Class
