'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace OrgChart.IntegrationWithRadToolTip
    
    Partial Public Class frm_HistorialComentarios
        
        '''<summary>
        '''lblt_titulo_pantalla control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_titulo_pantalla As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_subtitulo_pantalla control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_subtitulo_pantalla As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''h_Filter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents h_Filter As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''lblIDocumento0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIDocumento0 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblIDocumento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIDocumento As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblIDocumento1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIDocumento1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblAppIDocumento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAppIDocumento As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblIdRuta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIdRuta As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_IdCodigoAPP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_IdCodigoAPP As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_categoria1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_categoria1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_IdCodigoSAP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_IdCodigoSAP As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_status control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_status As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_category control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_category As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_categoria control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_categoria As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_approval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_approval As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_aprobacion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_aprobacion As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_Level control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_Level As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_nivelaprobacion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_nivelaprobacion As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_condition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_condition As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_condicion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_condicion As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_tipoDocumento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_tipoDocumento As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_tipoDocumento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_tipoDocumento As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_proccess_name control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_proccess_name As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_proceso control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_proceso As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_proccess_code control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_proccess_code As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_codigo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_codigo As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_instrument_number control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_instrument_number As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_instrumento control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_instrumento As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_beneficiary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_beneficiary As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_beneficiario control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_beneficiario As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_Datedcreated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_Datedcreated As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_datecreated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_datecreated As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_dateApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_dateApproved As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_dateapproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_dateapproved As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_ErrApprovedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_ErrApprovedBy As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_createdBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_createdBy As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_createdby control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_createdby As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblt_approvedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblt_approvedBy As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_approvedby control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_approvedby As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''tblt_status control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblt_status As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_status2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_status2 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbl_comment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_comment As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''btn_guardar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btn_guardar As Global.Telerik.Web.UI.RadButton
        
        '''<summary>
        '''RadOrgChartML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadOrgChartML As Global.Telerik.Web.UI.RadOrgChart
        
        '''<summary>
        '''RadToolTipManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadToolTipManager1 As Global.Telerik.Web.UI.RadToolTipManager
    End Class
End Namespace
