'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_ActivityEvaluation

    '''<summary>
    '''MsgGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgGuardar As Global.RMS_APPROVAL.ModalConfirm

    '''<summary>
    '''MsgReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgReturn As Global.RMS_APPROVAL.DeleteConfirm

    '''<summary>
    '''lblt_titulo_pantalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_titulo_pantalla As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_subtitulo_pantalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_subtitulo_pantalla As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_informacionproyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_informacionproyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_id_sesion_temp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_id_sesion_temp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''identity_sol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents identity_sol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''identity_doc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents identity_doc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''alink_ActivityTIME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_ActivityTIME As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''timeline_activity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeline_activity As Global.RMS_APPROVAL.ctrl_timeline_activity

    '''<summary>
    '''alink_definicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_definicion As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_solicitation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_solicitation As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_prescreening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_prescreening As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_submission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_submission As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_evaluation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_evaluation As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_awarded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_awarded As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_documentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_documentos As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_funding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_funding As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_DELIVERABLES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_DELIVERABLES As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''alink_INDICATORS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alink_INDICATORS As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_id_ficha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_id_ficha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_id_sol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_id_sol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_id_sol_app control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_id_sol_app As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''H_ID_APPLY_EVALUATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ID_APPLY_EVALUATION As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_ID_APPLY_APP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ID_APPLY_APP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_ID_EVALUATION_APP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ID_EVALUATION_APP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_ID_SOLICITATION_APP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ID_SOLICITATION_APP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_ID_EVALUATION_ROUND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ID_EVALUATION_ROUND As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_ID_ACTIVITY_SOLICITATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ID_ACTIVITY_SOLICITATION As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_COMM_TYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_COMM_TYPE As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_POINTS_VAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_POINTS_VAL As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''H_MAX_POINTS_SEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_MAX_POINTS_SEL As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTab As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Hiddenindi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hiddenindi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblt_solicitation_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_solicitation_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCodigo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_COde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_COde As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_Activity_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Activity_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_activity_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_activity_code As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblt_solicitation_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_solicitation_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmb_solicitation_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_solicitation_type As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblt_solicitation_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_solicitation_status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmb_solicitation_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_solicitation_status As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblt_fecha_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_fecha_inicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fecha_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fecha_inicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_fecha_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_fecha_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fecha_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fecha_final As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_Tittle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Tittle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_tittle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tittle As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RequiredFieldValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator4 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lbl_purpose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purpose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_purpose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_purpose As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RequiredFieldValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator5 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblt_solicitation_content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_solicitation_content As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_solicitation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_solicitation As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grd_support_Documents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_support_Documents As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''Repeater_Organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater_Organization As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblt_apply_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_apply_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_apply_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_apply_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_apply_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_apply_status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''spanSTATUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanSTATUS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_apply_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_apply_status As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Apply_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Apply_time As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_ORganization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_ORganization As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_organization As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_status_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_status_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_status_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_status_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AppDOCUMENTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AppDOCUMENTS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Lblt_Documents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lblt_Documents As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_archivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_archivos As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''app_History control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents app_History As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rept_ApplyDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rept_ApplyDates As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblt_guidelines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_guidelines As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_guidLines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_guidLines As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lblt_eval_start_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_eval_start_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_evaluation_startDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_evaluation_startDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_eval_End_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_eval_End_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_evaluation_EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_evaluation_EndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''EVAL_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EVAL_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_rounds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_rounds As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grd_rounds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_rounds As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblt_team_member control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_team_member As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grd_team control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_team As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblt_eval_document_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_eval_document_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grd_eval_Document control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_eval_Document As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lbl_round_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_round_number As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_round_organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_round_organization As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_round_start_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_round_start_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_round_startDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_round_startDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''H_ROUND_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H_ROUND_ID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblt_round_End_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_round_End_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_round_endDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_round_endDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_Selected_Applications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Selected_Applications As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_app_tot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_app_tot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_voting_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_voting_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_voting_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_voting_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_votes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_votes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tot_votes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tot_votes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_Total_Points control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Total_Points As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_total_points control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_points As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_Max_points control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Max_points As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_max_points control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_max_points As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''app_History_eval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents app_History_eval As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rept_ApplyDates_eval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rept_ApplyDates_eval As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''conflicto_intereses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conflicto_intereses As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_conflicto_intereses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_conflicto_intereses As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbn_conflicto_intereses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbn_conflicto_intereses As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btn_conflicto_intereses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_conflicto_intereses As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Buttons_approve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Buttons_approve As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''app_comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents app_comm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_approvalComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_approvalComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Editor_eval_comments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Editor_eval_comments As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblt_error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_error As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnlk_comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_comment As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_test control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_test As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_evaluate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_evaluate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_accept_Evaluation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_accept_Evaluation As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_testII control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_testII As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bntlk_accept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntlk_accept As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_OK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_OK As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_Untied control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_Untied As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_DISMISS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_DISMISS As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_Untied_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_Untied_Review As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''div_aggregate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_aggregate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnlk_Aggregate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_Aggregate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblt_values_err control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_values_err As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''esp_ctrl_h4_eliminar_titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents esp_ctrl_h4_eliminar_titulo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''esp_ctrl_lbl_eliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents esp_ctrl_lbl_eliminar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_eliminarDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_eliminarDocumento As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''esp_ctrl_btnh_CANCELAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents esp_ctrl_btnh_CANCELAR As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''H1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_msn_tasa_cambio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_msn_tasa_cambio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_registrar_tc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_registrar_tc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''rdEvaluation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdEvaluation As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''dv_answers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dv_answers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''H2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_Eval_Round control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Eval_Round As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_round control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_round As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''H3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_Applicant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_Applicant As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_asses_organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_asses_organization As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''H4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblt_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_amount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_amount_LOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amount_LOC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_screening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_screening As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_comentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_comentarios As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''RequiredFieldValidator12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator12 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''btnlk_eval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_eval As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnlk_cancel_eval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlk_cancel_eval As Global.System.Web.UI.WebControls.LinkButton
End Class
