'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_ProyectosRep

    '''<summary>
    '''lblt_codigo_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_codigo_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_codigo_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigo_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_estado_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_estado_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_estado_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_estado_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_nombre_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_nombre_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_nombre_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nombre_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_descripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_descripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_fecha_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_fecha_inicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fecha_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fecha_inicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_fecha_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_fecha_fin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fecha_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fecha_fin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_region control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_region As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_region control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_region As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_subregion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_subregion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_subregion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subregion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_componente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_componente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_componente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_componente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_ejecutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_ejecutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ejecutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ejecutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_codigoAID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_codigoAID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_codigoAID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigoAID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_municipios_atendidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_municipios_atendidos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_municipios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_municipios As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblt_sectores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_sectores As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_sectores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_sectores As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblt_indicadores_meta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_indicadores_meta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_indicadores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_indicadores As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblt_aportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_aportes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_aportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_aportes As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lblt_total_aporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_total_aporte As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_total_aporteUSD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_total_aporteUSD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_totalUSD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_totalUSD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_documentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_documentos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdArchivos As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''SqlDataSource7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource7 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblt_imagenes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_imagenes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GrdArchivosImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdArchivosImg As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''SqlDataSource8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource8 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
