'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_ProyectoAvanceMetasPrintInfo

    '''<summary>
    '''lblt_codigo_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_codigo_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_codigoSAPME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigoSAPME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_id_ficha_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_id_ficha_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_estado_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_estado_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_estadoFicha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_estadoFicha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_nombre_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_nombre_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_proyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_proyecto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_descripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_descripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_fecha_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_fecha_inicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fechainicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fechainicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_fecha_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_fecha_fin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fechafin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fechafin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_region control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_region As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_region control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_region As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_subregion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_subregion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_subregion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subregion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_componente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_componente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_componente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_componente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_ejecutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_ejecutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ejecutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ejecutor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_codigoAID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_codigoAID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_periodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_periodo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_periodoActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodoActivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblt_activo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblt_activo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_periodoActivoSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodoActivoSN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''img_periodoActivoSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_periodoActivoSN As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_periodoActivoEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodoActivoEstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''img_periodoActivoEstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_periodoActivoEstatus As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_codigoAID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigoAID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_codigoRFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigoRFA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_periodoActivoEstatusSync control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_periodoActivoEstatusSync As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''img_periodoActivoEstatusSync control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_periodoActivoEstatusSync As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tasaCambio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tasaCambio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblproyecto18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblproyecto18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TreeViewMetas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TreeViewMetas As Global.Telerik.Web.UI.RadTreeView

    '''<summary>
    '''SqlDataSource9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource9 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
