'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_viaje_facturacionPrint

    '''<summary>
    '''imgChemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgChemo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_subtitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_nombres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nombres As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_numero_documento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_numero_documento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_cargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cargo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_fecha_solicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fecha_solicitud As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_regional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_regional As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_codigo_viaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_codigo_viaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_observaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_observaciones As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_facturacion_alquiler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_facturacion_alquiler As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''grd_facturacion_tiquetes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_facturacion_tiquetes As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''grd_vuelos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_vuelos As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''grd_hotel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_hotel As Global.Telerik.Web.UI.RadGrid
End Class
